item_requests/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
        RequestCreationView,
        RequestDetailsView,
       RequestUpdateView,
       AddPaymentRequestView,
       ReviewPaymentView
)

urlpatterns = [
    path('create/', RequestCreationView.as_view(), name='create'),
    path('<slug>/', RequestDetailsView.as_view(), name='detail'),
    path('update/<slug>', RequestUpdateView.as_view(), name='update'),
    path('payment/<slug>', AddPaymentRequestView.as_view(), name='add'),
    path('payment/review/<slug>',ReviewPaymentView.as_view(), name='review')



]

layawayDemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from .views import home_page #about_page, contact_page,  register_page,
from authentication.views import login_page #
from profiles.views import UserProfileView
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
#from carts.views import cart_home



urlpatterns = [
        path('', home_page, name='homepage'),
        path('login/', login_page, name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('profile/', include(("profiles.urls",  'profiles'), namespace='profiles')),
        path('request/', include(("item_requests.urls", 'request'), namespace='request')),
        path('dashboard/', include(("dashboard.urls",  'dashboard'), namespace='dashboard')),
        path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from django.urls import path



from .views import  (
UserProfileView,
UserProfileEditView
)

urlpatterns = [
    path('', UserProfileView.as_view(), name='view'),
    path('edit/', UserProfileEditView.as_view(), name='edit'),

]

item_requests/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from decimal import Decimal
from django.forms import ModelForm, Textarea, TextInput, ChoiceField, NumberInput, CheckboxInput, Select, SelectDateWidget
from django import forms
from django.urls import reverse
from layawayDemo.utils import unique_order_id_generator, unique_slug_generator
from django.db.models.signals import pre_save


REQUEST_STATUS = (
        ('pending', 'Pending'),
        ('under_review', 'Under Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
)
class Request(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
        reference_ID = models.CharField(max_length=250, blank=True, default='xxx')
        url = models.CharField(max_length=250, blank=True, null=True)
        status = models.CharField(max_length=50, choices=REQUEST_STATUS, default='pending')
        slug = models.SlugField(blank=True, unique=True)
        title = models.CharField(max_length = 120, default='layaway request')
        submission_date = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        purchase_date = models.DateTimeField(blank=True, null=True)
        notes = models.CharField(max_length=250, blank=True, null=True)
        price =models.DecimalField(decimal_places=2, max_digits=20, default=00.00)
        remaining_amount = models.DecimalField(decimal_places=2, max_digits=20, default=00.00)
        payment_amount = models.DecimalField(decimal_places=2, max_digits=20, default=00.00)
        downpayment_paid = models.BooleanField(default=False)


        def __str__(self):
                return str( self.status)

        def get_absolute_url(self):
                return reverse("request:detail", kwargs={"slug": self.slug})

        @property
        def downpayment_amount(self):
                downpayment = round(self.price * Decimal(.35), 2)
                return downpayment


class RequestForm(ModelForm):
        """Form definition for Request."""

        class Meta:
                """Meta definition for Requestform."""

                model = Request
                fields = ('url', 'notes')
                widgets = {
                        'url': TextInput(attrs={"class": "form-control"}),
                        'notes': Textarea(attrs={"cols":80, "rows":4, "class": "form-control"})
                }

class UpdateRequestForm(ModelForm):
        """Form definition for UpdateRequest."""

        class Meta:
                model = Request
                fields = ('status', 'title', 'notes', 'purchase_date',  'price', 'remaining_amount', 'payment_amount', 'downpayment_paid')
                widgets = {
                        'status': Select(attrs={"class": "form-control"}),
                        'title': TextInput(attrs={"class": "form-control"}),
                        'price': TextInput(attrs={"class": "form-control"}),
                        'purchase_date': SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"), attrs={"class": "form-control"}),
                        'remaining_amount': NumberInput( attrs={"class": "form-control"}),
                        'payment_amount': NumberInput(attrs={"class": "form-control"}),
                        'downpayment_paid': CheckboxInput( attrs={"class": "form-control"}),
                        'notes': Textarea(attrs={"cols":80, "rows":4, "class": "form-control"})
                }



@receiver(pre_save, sender=Request)
def pre_save_request_receiver(sender, instance, *args, **kwargs):
        if not instance.slug:
                instance.slug = unique_slug_generator(instance)
        if not instance.reference_ID:
                instance.reference_ID = unique_order_id_generator(instance)

item_requests/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from .models import RequestForm, Request, UpdateRequestForm
import stripe
from django.conf import settings
from django.core.mail import send_mail

# Create your views here.

class RequestCreationView(FormView):
        template_name="request/create.html"
        request_form_class = RequestForm

        def get(self, request, *args, **kwargs):
                request_form_obj = self.request_form_class()
                return render(request, self.template_name, {
                        "request_form": request_form_obj
                })

        def post(self, request, *args, **kwargs):
                user = request.user
                new_request_form = RequestForm(request.POST)
                if new_request_form.is_valid():
                        new_request = new_request_form.save(commit=False)
                        new_request.user = user
                        new_request.save()
                        return redirect("dashboard:view")

                return render(request, "dashboard/view.html", {})

class AddPaymentRequestView(View):
        template_name="payment/create.html"

        def get(self, request, *args, **kwargs):
                user = request.user
                slug = self.kwargs.get('slug')
                #put a try block to get the right request object, if the user and the slug dont match, redirect the user to their dashboard
                try:
                        request_obj = Request.objects.get(user = user, slug=slug)
                except Request.DoesNotExist:
                        print("You are not the right user for this request")
                        return redirect("dashboard:view")
                else:
                        #request_obj = Request.objects.get(user = user)
                        # request_update_form = self.request_form_class(instance=request_obj)
                        return render(request, self.template_name, {
                                "request_obj": request_obj
                        })

        def post(self, request, *args, **kwargs):
                user = request.user
                slug = self.kwargs.get('slug')
                try:
                        request_obj = Request.objects.get(user = user, slug=slug)
                        amount_to_pay = request.POST.get("payment_amount")
                        request_obj.payment_amount = amount_to_pay
                        request_obj.save()
                except Request.DoesNotExist:
                        print("You are not the right user for this request")
                        return redirect("dashboard:view")
                else:
                        return redirect("request:review", slug=slug) #change to redirect to the review.html page once it has been plugged in

class ReviewPaymentView(View):
        template_name = "payment/review.html"

        def get(self, request, *args, **kwargs):
                user = request.user
                slug = self.kwargs.get('slug')
                try:
                        request_obj = Request.objects.get(user = user, slug=slug)
<<<<<<< HEAD
                        if request_obj.downpayment_paid:
                                stripe_amount = request_obj.payment_amount *100
                                current_payment_amount = request_obj.payment_amount
                        else:
                                stripe_amount = request_obj.down_payment_amount * 100
                                current_payment_amount = request_obj.down_payment_amount

=======
                        stripe_amount = request_obj.payment_amount * 100
>>>>>>> origin/master
                except Request.DoesNotExist:
                        print("You are not the right user for this request")
                        return redirect("dashboard:view")
                else:
                        return render(request, self.template_name, {
                                "request_obj": request_obj,
                                "stripe_amount": stripe_amount
                        })

        def post(self, request, *args, **kwargs):
                user = request.user
                print(request.POST)
                slug = self.kwargs.get('slug')
                try:
                        request_obj = Request.objects.get(slug=slug, user = user)
                        payment_amount = request_obj.payment_amount
                        stripe.api_key = settings.STRIPE_SECRET_KEY
                        token = request.POST.get('stripeToken')
                        user_email = request.POST.get('stripeEmail')
                        stripe_payment_amount = int(request_obj.payment_amount)*100
                        customer = stripe.Customer.create(
                                email=user_email,
                                source = token
                        )
                        charge = stripe.Charge.create(
                                amount = stripe_payment_amount,
                                currency = "eur",
                                description = "New layaway payment",
                                customer = customer.id
                        )
                except stripe.error.CardError as e:
                        return False, e
                except Request.DoesNotExist:
                        print("You are not the right user for this request")
                        return redirect("dashboard:view")
                else:
                        #Payment was successful, handle any clean-up and processing
                        request_obj.payment_amount = 0.00
                        request_obj.remaining_amount -= payment_amount
                        request_obj.save()
                        #TODO:: Send a confirmation email to the user, and a notification email to the admins
                        return redirect("dashboard:view")



class RequestDetailsView(DetailView):
        model = Request
        template_name="request/detail.html"

        def get_object(self, *args, **kwargs):
                request = self.request
                user = request.user
                slug = self.kwargs.get('slug')
                try:
                        instance = Request.objects.get(slug=slug)
                except Request.DoesNotExist:
                        raise Http404("Not found..")
                except Request.MultipleObjectsReturned:
                        qs = Request.objects.filter(slug=slug)
                        instance = qs.first()
                except:
                        raise Http404("hmmmm")
                return instance


class RequestUpdateView(View):
        request_form_class = UpdateRequestForm
        template_name = 'request/request_update.html'

        def get(self, request, *args, **kwargs):
                user = request.user
                slug = self.kwargs.get('slug')
                request_obj = Request.objects.get(slug=slug)

                request_update_form = self.request_form_class(instance=request_obj)
                return render(request, self.template_name, {
                        'request_form': request_update_form
                })
        def post(self, request, *args, **kwargs):
                user = request.user
                slug=self.kwargs.get('slug')
                request_obj = Request.objects.get(slug=slug)

                request_form = self.request_form_class(request.POST, instance=request_obj)
                if request_form.is_valid():
                        downpayment =  request_form.cleaned_data['price'] * Decimal(0.35)
                        print(request_obj.downpayment_amount)
                        #request_form.cleaned_data['downpayment_amount'] = downpayment
                     #   request_form.cleaned_data['downpayment_amount'] =
                        if 'status' in request_form.changed_data:
                               # old_status = request_obj.status
                                # new_status = request.POST.get('status')
                                # send_mail(
                                #         'Testing for status changes',
                                #         'The status of your request has been updated to {0}. Please log-in to view your account'.format(new_status),
                                #         'haki.projects@gmail.com',
                                #         ['everettlrobinson@gmail.com'],
                                #         fail_silently=False,
                                # )


                                request_form.save()

                        #send an email to the Admins and User making the request of the updated status
                return redirect("dashboard:view")

item_requests/templates/request/create.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
        <div class="col">
                        <form method="POST">
                                        {% csrf_token %}
                                        {{ request_form }}
                                        <br />
                                        <button type="submit" class="btn btn-success">Create</button>
                                        <a class="btn btn-danger" href="{% url 'dashboard:view' %}">Cancel</a>
                        </form>
        </div>
</div>



{% endblock content %}

item_requests/templates/request/detail.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
        <div class="col">
<<<<<<< HEAD
                        <div class="card text-center">
                                                         <div class="card-header">
                                                        <b>Reference Number: </b> {{ object.reference_ID }}<br />
                                                       <b>Status:  </b>  {{ object.status}}
                                                         </div>
                                                         <div class="card-body">
                                                         <h5 class="card-title">{{ object.url }}</h5>
                                                         <p class="card-text"> {{ object.notes }}</p>



                                                         {% if object.status == "approved" %}
                                                                 <ul class="list-group list-group-flush mx-4">
                                                                                 <li class="list-group-item"><b>Total Price:</b> {{ object.price }} <br />
                                                                                         {% if object.downpayment_paid is False %}
                                                                                                  <b>Down payment Amount:</b>{{ object.down_payment_amount }}
                                                                                         {% else %}
                                                                                                <b> Amount Owed:</b> {{ object.remaining_amount }}
                                                                                         {% endif %}

                                                                                 </li>

                                                                 </ul>
                                                         {% else %}
                                                         <ul class="list-group list-group-flush mx-4">
                                                                         <li class="list-group-item"><b>Total Price:</b> <i>{{ object.status }} </i><br />
                                                                         <b>Amount Owed:</b> <i>{{ object.status }}</i></li>
                                                         </ul>
                                                         {% endif %}




                                                         {% if is_admin %}
                                                         <a href="{% url 'request:update' slug=object.slug %}" class="btn btn-info">Update Request</a>
                                                         {% endif %}

                                                         </div>
                                                         <div class="card-footer text-muted">
                                                                 last updated {{ object.updated }}
                                                         </div>
        </div>
<br />
=======
                        {{ object.title }}
                        {{ object.status }}
        </div>
</div>
>>>>>>> origin/master
<h3> Request History</h3>



{% endblock content %}

item_requests/templates/request/request_update.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
        <div class="col">
                        <form method="POST">
                                        {% csrf_token %}
                                        {{ request_form }}
                                        <br />
                                        <button type="submit" class="btn btn-success">Update</button>
                                        <a class="btn btn-danger" href="{% url 'dashboard:view' %}">Cancel</a>
                        </form>
        </div>
</div>



{% endblock content %}