layawayDemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from .views import home_page #about_page, contact_page,  register_page,
from authentication.views import login_page #
from profiles.views import UserProfileView
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
#from carts.views import cart_home



urlpatterns = [
        path('', home_page, name='homepage'),
        path('login/', login_page, name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('profile/', include(("profiles.urls",  'profiles'), namespace='profiles')),
        path('request/', include(("item_requests.urls", 'request'), namespace='request')),
        path('dashboard/', include(("dashboard.urls",  'dashboard'), namespace='dashboard')),
        path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from django.urls import path



from .views import  (
UserProfileView,
UserProfileEditView
)

urlpatterns = [
    path('', UserProfileView.as_view(), name='view'),
    path('edit/', UserProfileEditView.as_view(), name='edit'),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import ModelForm, Textarea, TextInput
from django import forms


USER_ROLES = (
        ('admin', 'Administrator'),
        ('contributor', 'Contributor'),
        ('default_user', 'Default User')
)

class BillingAddress(models.Model):
        username = models.CharField(max_length=250, blank=True)
        address_line_1 = models.CharField(max_length=250, blank=True)
        address_line_2 = models.CharField(max_length=250, blank=True)
        city = models.CharField(max_length=250, blank=True)
        state = models.CharField(max_length=250, blank=True)
        postal_code = models.CharField(max_length=250, blank=True)

        def __str__(self):
                return str(self.username + ' - Billing Address')

class ShippingAddress(models.Model):
        username = models.CharField(max_length=250, blank=True)
        address_line_1 = models.CharField(max_length=250, blank=True)
        address_line_2 = models.CharField(max_length=250, blank=True)
        city = models.CharField(max_length=250, blank=True)
        state = models.CharField(max_length=250, blank=True)
        postal_code = models.CharField(max_length=250, blank=True)
        def __str__(self):
                return str(self.username + ' - Shipping Address')

class Profile(models.Model):
        user = models.OneToOneField(User, on_delete=models.CASCADE)
        email = models.EmailField(max_length=250, blank=True)
        first_name = models.CharField(max_length=250, blank=True)
        last_name = models.CharField(max_length=250, blank=True)
        role = models.CharField(max_length=100, choices=USER_ROLES, default='default_user')
        cell_number = models.CharField(max_length=250, blank=True)
        # photo =
        billing_address = models.OneToOneField(BillingAddress, null=True, on_delete=models.CASCADE)
        shipping_address = models.OneToOneField(ShippingAddress, null=True, on_delete=models.CASCADE)
        bio = models.TextField(max_length=500, blank=True)

        def __str__(self):
                return str(self.user.username)

class ProfileForm(ModelForm):
        """Form definition for Profile."""

        class Meta:
                model = Profile
                fields = ('email','first_name', 'last_name', 'cell_number', 'bio')
                widgets = {
                'email': TextInput(attrs={"class": "form-control"}),
                'first_name': TextInput(attrs={"class": "form-control"}),
                'last_name': TextInput(attrs={"class": "form-control"}),
                'cell_number': TextInput(attrs={"class": "form-control"}),
                'bio': Textarea(attrs={"cols":80, "rows":4, "class": "form-control"})
                }

class ShippingAddressForm(ModelForm):
        """Form definition for ShippingAddress."""

        class Meta:
                """Meta definition for ShippingAddressform."""

                model = ShippingAddress
                fields = ('address_line_1', 'address_line_2', 'city', 'state', 'postal_code')
                widgets = {
                        'address_line_1': TextInput(attrs={"class": "form-control"}),
                        'address_line_2': TextInput(attrs={"class": "form-control"}),
                        'city': TextInput(attrs={"class": "form-control"}),
                        'state': TextInput(attrs={"class": "form-control"}),
                        'postal_code': TextInput(attrs={"class": "form-control"}),
                }

class BillingAddressForm(ModelForm):
        """Form definition for BillingAddress."""

        class Meta:
                """Meta definition for BillingAddressform."""

                model = BillingAddress
                fields = ('address_line_1', 'address_line_2', 'city', 'state', 'postal_code')
                widgets = {
                        'address_line_1': TextInput(attrs={"class": "form-control"}),
                        'address_line_2': TextInput(attrs={"class": "form-control"}),
                        'city': TextInput(attrs={"class": "form-control"}),
                        'state': TextInput(attrs={"class": "form-control"}),
                        'postal_code': TextInput(attrs={"class": "form-control"}),
                }





@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
        if created:
                new_shipping_address = ShippingAddress.objects.create(username=instance.username)
                new_billing_address = BillingAddress.objects.create(username=instance.username)
                Profile.objects.create(user=instance, billing_address=new_billing_address, shipping_address=new_shipping_address)

profiles/forms.py
#create a form based off of the Profile Model
# from django.forms import ModelForm

# from .models import Profile

# class ProfileForm(ModelForm):
#         """Form definition for Profile."""

#         class Meta:
#                 model = Profile
#                 fields = ('email','first_name', 'last_name')

profiles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import ProfileForm, Profile, ShippingAddress, ShippingAddressForm, BillingAddress, BillingAddressForm

class UserProfileView(View):
        profile_form_class = ProfileForm
        template_name = "profile/user_view.html"
        greeting = "hello and welcome"
        # user = get currently logged in user


        def get(self, request, *args, **kwargs):
                user = request.user
                profile = Profile.objects.get(pk=user.id)
                profile_object = self.profile_form_class(instance=profile)
                #form = self.profile_form_class()
                print(profile)
                return render(request, self.template_name, {
                        "greeting": self.greeting,
                         "profile": profile})



class UserProfileEditView(View):
        profile_form_class = ProfileForm
        shipping_address_form_class = ShippingAddressForm
        billing_address_form_class = BillingAddressForm
        template_name = "profile/user_edit.html"
        greeting = "hello and welcome"
        # user = get currently logged in user


        def get(self, request, *args, **kwargs):
                user = request.user
                profile = Profile.objects.get(pk=user.id)
                shipping_address = ShippingAddress.objects.get(username=user.username)
                billing_address = BillingAddress.objects.get(username=user.username)

                profile_form = self.profile_form_class(instance=profile)
                shipping_address_form = self.shipping_address_form_class(prefix='ship', instance=shipping_address)
                billing_address_form = self.billing_address_form_class(prefix='bills', instance=billing_address)
                return render(request, self.template_name, {
                        "greeting": self.greeting,
                        "profile_form": profile_form,
                        "shipping_form": shipping_address_form,
                        "billing_form": billing_address_form
                        }
                        )
        def post(self, request, *args, **kwargs):
                #get the currect instance of each of the objects being edited
                user = request.user
                profile = Profile.objects.get(pk=user.id)
                shipping_address = ShippingAddress.objects.get(username=user.username)
                billing_address = BillingAddress.objects.get(username=user.username)
                #Get the form data being changed
                profile_form = self.profile_form_class(request.POST, instance=profile)
                shipping_form = self.shipping_address_form_class(request.POST, instance=shipping_address, prefix='ship')
                billing_form = self.billing_address_form_class(request.POST, instance= billing_address, prefix='bills' )
                #validate form data and update the object
                if profile_form.is_valid() and shipping_form.is_valid() and billing_form.is_valid():
                        shipping_form.save()
                        billing_form.save()
                        profile_form.save()
                        pass

                return render(request, self.template_name, {
                        "greeting": self.greeting,
                        "profile_form": profile_form,
                        "shipping_form": shipping_form,
                        "billing_form": billing_form
                        }
                        )

profiles/templates/profile/user_edit.html
{% extends 'base.html' %}


{% block content %}
        <div class="row">
        <div class="col">
            <div class="col-sm-6 col-12 mx-auto">
                <form method="POST">
                {% csrf_token %}
                <h2> Profile </h2>
                  <hr />
                {{ profile_form }}

               <h2> Shipping Address</h2>
                  <hr />
                {{ shipping_form }}

                <h2> Billing Address </h2>
                  <hr />
                {{ billing_form }}
                <br />
                {% comment %} <button type="submit" class="btn btn-info">Save and Continue Editing</button> {% endcomment %}
                <button type="submit" class="btn btn-success">Save</button>
                <a class="btn btn-danger" href="{% url 'profiles:view' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

profiles/templates/profile/user_view.html
{% extends 'base.html' %}


{% block content %}
        <div class="row">
        <div class="col">
            <div class="col-sm-6 col-12 mx-auto">
        <div class="card" style="width: 25rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">
                {% if profile.first_name %}
                        <h2>  Welcome {{profile.first_name}} ! </h2>
                {% else %}
                                        Welcome
                {% endif %}
    </h5>
    <p class="card-text">{{ profile.bio}}</p>
    <a href="#" class="card-link "><i class="far fa-edit"></i></a>
  </div>
  <div class="card-header"><b> Basic info </b></div>
  <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <i class="far fa-user"></i>
            {% if profile.first_name or profile.last_name %}
                        {{ profile.first_name}}  {{ profile.last_name }}
            {% else %}
                -
            {% endif %}
    </li>
    <li class="list-group-item">
            <i class="far fa-envelope"></i>
            {% if   profile.email  %}
                {{ profile.email }}
            {% else %}
                 -
            {% endif %}
    </li>
    <li class="list-group-item">
            <i class="fas fa-phone"></i>
                {% if profile.cell_number %}
                        {{ profile.cell_number}}
                {% else %}
                        -
                {% endif %}
    </li>
     <div class="card-header"> <b> Shipping Address </b></div>
                <ul class="list-group list-group-flush">
                        <li class="list-group-item"> Address: {{ profile.shipping_address.address_line_1 }}</li>
                        <li class="list-group-item"> Address Line (optional): {{ profile.shipping_address.address_line_2 }}</li>
                        <li class="list-group-item">City: {{ profile.shipping_address.city }}</li>
                        <li class="list-group-item">State: {{ profile.shipping_address.state  }}</li>
                        <li class="list-group-item"> Postal Code:  {{  profile.shipping_address.postal_code }}</li>

     <div class="card-header"> <b> Billing Address </b></div>
                        <li class="list-group-item"> Address Line {{ profile.billing_address.address_line_1 }}</li>
                        <li class="list-group-item"> Address Line (optional)  {{ profile.billing_address.address_line_2 }}</li>
                        <li class="list-group-item">City {{ profile.billing_address.city }}</li>
                        <li class="list-group-item">State {{ profile.billing_address.state }}</li>
                        <li class="list-group-item"> Postal Code {{ profile.billing_address.postal_code }} </li>
</ul>
<div class="card-body">
        <a href="{% url 'profiles:edit' %}" class="card-link">Edit</a>
</div>

</div>

            </div>
        </div>
    </div>
{% endblock content %}