layawayDemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from .views import home_page #about_page, contact_page,  register_page,
from authentication.views import login_page #
from profiles.views import UserProfileView
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
#from carts.views import cart_home



urlpatterns = [
        path('', home_page, name='homepage'),
        path('login/', login_page, name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('profile/', include(("profiles.urls",  'profiles'), namespace='profiles')),
        path('request/', include(("item_requests.urls", 'request'), namespace='request')),
        path('dashboard/', include(("dashboard.urls",  'dashboard'), namespace='dashboard')),
        path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from django.urls import path



from .views import  (
UserProfileView,
UserProfileEditView
)

urlpatterns = [
    path('', UserProfileView.as_view(), name='view'),
    path('edit/', UserProfileEditView.as_view(), name='edit'),

]

layawayDemo/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render, redirect
from django.http import HttpResponse

# from .forms import ContactForm
# from .forms import LoginForm, RegisterForm


def home_page(request):
  context = {
    "title": "Hello from the homepageeeee",
     "premium_content": "Yeeaaaahhhh premium content!",
  }
  if request.user.is_authenticated:
    print("user is authenticated")

  return render(request, "home_page.html", context)

layawayDemo/templates/base.html
{% load static %}
{% url 'homepage' as homepage_url %}
{% url 'contact' as contact_url  %}
{% url 'about' as about_url  %}
{% url 'products:list' as products_url  %}
{% url 'dashboard:view' as dashboard_url %}
{% url 'login' as login_url  %}
{% url 'logout' as logout_url  %}
{% url 'register' as register_url  %}
{% url 'cart:home' as cart_url %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'css/main.css' %}">

    <!-- Fontawesome CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <title>Layaway</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
        <a class="navbar-brand" href="#">Layaway Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
                <li class="nav-item">
                        <a class="nav-link" href="#">About<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="#">Products</a>
                <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                </li>
</ul>
<ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}

      <li class="nav-item dropdown mx-auto">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.username }} <i class="fas fa-2x fa-user-circle"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <a class="dropdown-item" href="{{ dashboard_url }}">Your Dashboard</a>
          <a class="dropdown-item" href="{% url 'profiles:view' %}">Your Profile</a>
          <a class="dropdown-item disabled" href="#">Your Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger" href="{% url 'logout'  %}">Logout</a>
        </div>
      {% else %}
        <li class="nav-item">
                <a class="nav-link" href="{% url 'login'  %}">Login</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="#">Register</a>
        </li>
      {% endif %}
      </li>
                <li class="nav-item">
                        <a class="nav-link" href="#">
                                {% if request.session.cart_items %}
                                        {{ request.session.cart_items }}
                                {% else %}
                                {% endif %}
                <i class="fas fa-2x  fa-shopping-cart"></i></a>
                </li>
    </ul>
    <div class="ml-auto">

  </div>
  </div>
</nav>
  <div class="container" >

{% block content %}

{% endblock content %}

</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

layawayDemo/templates/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

 <title>Home template</title>
  </head>
  <body>
    <h1>Hello, world from templates!</h1>
    <img src="{% static 'img/beads.png' %}" class= "img-fluid">



    <div class= "container">



{% if request.user.is_authenticated %}
  <div class="row">
        <div class="col"></div>
     </div>
{% endif %}


    </div>


{% endblock content %}